### ISSUE TITLE
This package cannot be require'd

### ISSUE THREAD

**Issue by swflint** [dalanicolai/pdf-continuous-scroll-mode.el#1]
This package looks great, but if I have to directly use `load`, I won't use it.  Adding a `provide` and the necessary `require` statements would make it much better (and make it easier to eventually get into MELPA).

**Comment by dalanicolai** [comment]
Ah yeah, thanks for the feedback! I will add the provide as I guess you are right that adding a provide would probably make sense. Although I am not sure what advantages it will provide over `eval-after-load (load "pdf-view")` (should read/think once more about require and provide), as you need to load pdf-view for using this package anyway.
Also I am not sure if I will put in all the work to get it to MELPA, as I consider the two buffer solution a little too hacky for MELPA anyway.

**Comment by dalanicolai** [comment]
Okay, I see that require adds it to the loaded features. It looks a little cleaner indeed.
I have added the `provide` and updated the README, so I will close this issue. Thanks again!
