### ISSUE TITLE
void function about pdf-continuous-scroll-mode

### ISSUE THREAD

**Issue by rifiuto** [dalanicolai/pdf-continuous-scroll-mode.el#14]
Today, I open the pdf file, they give a message, `Symbol's value as variable is void: pdf-continuous-scroll-mode`, I don't know how to solve it.

**Comment by rifiuto** [comment]
`File mode specification error: (void-function pdf-continuous-scroll-mode)` just like this.

**Comment by dalanicolai** [comment]
I guess you must have updated your packages. I have rewritten and updated pdf-continuous-scroll-mode.el; despite the name, I have removed the mode. I guess you are adding `pdf-continuous-scroll-mode` to the `pdf-view-mode-hook` somewhere in your init/config file. You should not do that anymore (i.e. remove the line from your init file).

The new continuous scroll does not work flawlessly yet, but I hope by releasing it, other users will jump in to fix bugs.

If you would like to use the previous '2-buffer hack' continuous scroll, then you can download and load the old `pdf-continuous-scroll-mode.el` from [here](https://github.com/dalanicolai/pdf-continuous-scroll-mode.el/blob/79410ebe476445db28d5cc7a144f2d2f55dd70b0/pdf-continuous-scroll-mode.el).

**Comment by rifiuto** [comment]
Thank you for your answer, just as you said, I install the lastest package.

**Comment by dalanicolai** [comment]
Closing the issue for archiving this repo. A better implementation is available at https://github.com/dalanicolai/image-roll.el
