### ISSUE TITLE
switch window forces pdf to go to the first page or even go blank

### ISSUE THREAD

**Issue by pulledlamb** [dalanicolai/pdf-continuous-scroll-mode.el#16]
Here is a gif showing the issue.
![pdf-continuous](https://user-images.githubusercontent.com/81538877/153190611-f72700a5-391e-482a-a8b2-85587d32a837.gif)

and my configs are as 
```
;; (pdf-tools-install)
(use-package pdf-tools
  :ensure t
  ;; :commands (pdf-view-mode pdf-loader-install)
  :mode ("\\.[pP][dD][fF]\\'" . pdf-view-mode)
  :magic ("%PDF" . pdf-view-mode)
  :config
  (pdf-tools-install)
  (define-pdf-cache-function pagelables)
  ;;In case of high-resolution screen like Mac
  (setq pdf-view-use-scaling t
	pdf-view-use-imagemagick nil)
  :hook
  (pdf-view-mode . (lambda ()
		     (display-line-numbers-mode -1)))
  )
(add-hook 'TeX-mode-hook
	  #'(lambda ()
	      (setq TeX-view-program-selection
		    '((output-pdf "PDF Tools")))
              ;; (setq TeX-view-program-list
              ;;       '(("PDF Tools" TeX-pdf-tools-sync-view)))
	      ))
(add-hook 'TeX-mode-hook
          #'(lambda ()
              (setq TeX-source-correlate-mode t)
              (with-eval-after-load "pdf-sync"
                (define-key TeX-source-correlate-map (kbd "C-c C-g")
                  'pdf-sync-forward-search))))

;;allow you to view pdf continuously
(use-package pdf-continuous-scroll-mode
  :straight (pdf-continuous-scroll-mode :type git :host github
					:repo "dalanicolai/pdf-continuous-scroll-mode.el")
  )
(setq pdf-continuous-suppress-introduction t)
(add-hook 'pdf-view-mode-hook 'pdf-continuous-scroll-mode)
(evil-define-key 'normal pdf-view-mode-map
  "j" 'pdf-continuous-scroll-forward
  (kbd "<down>") 'pdf-continuous-scroll-forward
  "gt" 'pdf-view-goto-page)
```

Any ideas how to fix it?

**Comment by workcomplete** [comment]
Did you fix this? having a similar issue when I switch focus by calling `org-noter-insert-precise-note`

**Comment by dalanicolai** [comment]
Indeed, would be interesting to hear why you closed this. Did you find a fix?

**Comment by pulledlamb** [comment]
> Indeed, would be interesting to hear why you closed this. Did you find a fix?



> Did you fix this? having a similar issue when I switch focus by calling `org-noter-insert-precise-note`

I'm soooo sorry guys. I didn't close because I have a fix;

I saw at Spacemacs that this seems to be a known issue with pdf-tools.... so decided to close it for now;

My bad...

**Comment by dalanicolai** [comment]
Thanks for the reply. The book-image-positions function is related to continuous scroll. However, I don't know how to solve these issues. I will write on the wiki an explanation how the continuous scroll (and doc/pdf-view display) works. I hope with the help of that explanation, users might be able to investigate and fix the issues themselves (or at least help with it).
