### ISSUE TITLE
Screen getting black for a while when using synctex double click

### ISSUE THREAD

**Issue by Sparsa** [dalanicolai/pdf-continuous-scroll-mode.el#18]
I use synctex to sync between my latex code and the output PDF. When I click on a word on pdf-tools it shows the correct word in the latex source. 
But,  it makes the screen black. Resizing Emacs brings back the output. 
in my setting, I have used 
(require 'pdf-continuous-scroll-mode) after the quelpa recipe.

**Comment by dalanicolai** [comment]
Thank you for reporting the issue. I am aware of such kind of 'redisplay' problems, and have mentioned these issues in [the comment section of the README](https://github.com/dalanicolai/pdf-continuous-scroll-mode.el#comments).
Unfortunately, finding out how the Emacs (re)display mechanism works takes a lot of time (actually, although this package only adds few lines of code, writing the current code already was more work than the work for any other package I wrote). The main reason for 'publishing' the code in its current state is that it might invite other smarter hackers to help solve these issues.

In the meantime you could alternatively use the 2-buffer hack from commit 79410ebe476445db28d5cc7a144f2d2f55dd70b0 (I think it works with synctex, although I am not sure)

I will probably create a kickstarter or something to let the community help me fix the code. I hope there is enough interest for it...

**Comment by dalanicolai** [comment]
Closing the issue for archiving this repo. A better implementation is available at https://github.com/dalanicolai/image-roll.el
