### ISSUE TITLE
Plans to upload to Melpa?

### ISSUE THREAD

**Issue by ianyepan** [dalanicolai/pdf-continuous-scroll-mode.el#2]
As titled, I'd love to install this from MELPA. Do you have plans to merge this package to MELPA upstream?

**Comment by dalanicolai** [comment]
I think this package is a little too hacky for MELPA, but I am willing to consider it. Is there some particular reason why you prefer to install from MELPA? 

Anyway I will keep the issue open so that people can thumb up your request.

**Comment by odanoburu** [comment]
I'm yet to read the code,  but I'd prefer it being added to pdf-tools itself, if the maintainers agree (and you, of course!)

i miss this functionality a lot, but it wouldn't have to be turned on by default or anything. tbh i don't even need the continuous view, just that the line I'm reading moves to where i expect it to when i scroll (which it does not when near the end of the page )

**Comment by dalanicolai** [comment]
I am completely fine with merging it with pdf-tools, actually I was considering it before publishing, but I decided that the two-buffer thing is a little too hacky, while also improving the quality of the code sufficiently and make it work smoothly with all of pdf-tools its features would take too much time for just some small (but convenient) improvement.
Anyway, I published it now as a minor mode first. Anybody is free to fork it or send PR's. And if we can improve the quality of the code sufficiently then we can send a merge request to pdf-tools.

**Comment by edumerco** [comment]
If waiting to improve the quality takes too much time, then MELPA is a great possibility. 
Thanks a lot for your work here. :+1:

**Comment by ianyepan** [comment]
> Is there some particular reason why you prefer to install from MELPA?

I like to stay updated with every package I install, so the main reason I'd like to install from MELPA would be that I could periodically M-x package update and pull changes. With the current approach, I'd have to manually copy paste the latest Elisp file from this repo (which isn't a big problem, I just need to remember to do this). From your point of view, your users will be missing the latest commits that you pushed here if they didn't come here and copy the changes manually every now and then.

> but I decided that the two-buffer thing is a little too hacky, while also improving the quality of the code sufficiently and make it work smoothly with all of pdf-tools its features would take too much time for just some small (but convenient) improvement.

I guess if the pdf tools maintainers like the idea, they could add it as an optional minor mode, so that only users who are willing to use this "hacky" code can turn this on. Doesn't affect the current status of pdf-tools, and is backwards compatible in a sense.

**Comment by ianyepan** [comment]
Anyhow, thanks so much for the effort! I'm so glad someone decided to implement this -- hacky or not -- as long as it works!

**Comment by dalanicolai** [comment]
@ianpan870102 Well that sounds like a good reason to me. Although it is also possible to stay updated by using [Quelpa recipes](https://github.com/quelpa/quelpa) like Spacemacs does (I am a Spacemacs user). Actually thanks for mentioning it, because now I will "upgrade" the README to recommend installing this package via a Quelpa recipe.

**Comment by dalanicolai** [comment]
I forgot to mention that the pdf-tools maintainers probably should be aware of this package as I posted this solution [in a long standing issue](https://github.com/politza/pdf-tools/issues/27#issuecomment-696237353) there first. Although I see now that Politza hasn't been very active on Github lately.

**Comment by Ypot** [comment]
> 
> 
> I forgot to mention that the pdf-tools maintainers probably should be aware of this package as I posted this solution [in a long standing issue](https://github.com/politza/pdf-tools/issues/27#issuecomment-696237353) there first. Although I see now that Politza hasn't been very active on Github lately.

https://www.reddit.com/r/emacs/comments/ip17pu/looking_for_a_maintainer_for_pdftoolstablist/

**Comment by dalanicolai** [comment]
Thanks for this notification. And huge thanks to Politza for his amazing work! PDF-tools and tablist are really two of the most useful Emacs packages. Together they provide the most powerful and hackable pdf reader, editor and note manager I know. I really wish new maintainers will step up. Of course I am willing to support as much as I can. But I am not a real developer and pdf-tools contains some quite advanced code. Anyway, I guess many people share my enthusiasm and there should be some that are happy to maintain these packages. Anyway, once more thanks to Politza for his great contribution!

**Comment by dalanicolai** [comment]
Closing the issue for archiving this repo. A better implementation is available at https://github.com/dalanicolai/image-roll.el
