### ISSUE TITLE
Does not work with scroll wheel

### ISSUE THREAD

**Issue by io12** [dalanicolai/pdf-continuous-scroll-mode.el#3]
This is a really cool mode! I tried it and it works great when scrolling with the arrow keys, but has the old behavior (snapping to the next page) when using the scroll wheel.

**Comment by dalanicolai** [comment]
Thanks for the positive feedback. I indeed am aware of this but I did not yet find out how to bind the scrolling wheel to the continuous scroll functions. Although now I realize that I did not even try to just bind it. I have only tried to figure out how the wheel is bound to the scroll functions in pdf-tools (and I could not find it). So I will look at it again...

**Comment by dalanicolai** [comment]
I have added the mouse-wheel bindings. It hangs on the mode-line, but you can hide the mode-line using `pdf-cscroll-toggle-mode-line` (see key-bindings table in README). I will close the issue.
