### ISSUE TITLE
natural scrolling?

### ISSUE THREAD

**Issue by Sparsa** [dalanicolai/pdf-continuous-scroll-mode.el#6]
Hi, I use natural scrolling and it works great with pdf-tools but it some how not working with this package, it uses conventional scrolling. It would be nice if there is a flag to resolve this issue (may be already there but I am not able to find it). This is a great work and highly appreciated, I was looking for some thing for a long time. Thank you.

**Comment by dalanicolai** [comment]
Hi, thanks for the feedback. I have added the customizable variable `pdf-cs-reverse-scrolling`. On my laptop the default setting is natural scrolling when using the touchpad and reverse scrolling when using the mouse wheel. So via this new variable you can reverse the direction for both. If you just want to reverse the direction for one of them then I guess you should just rebind the mouse keys/wheel.

**Comment by Sparsa** [comment]
Thanks, it is now working perfectly as I expected. Both on mouse and keyboard.

**Comment by dalanicolai** [comment]
:+1:
