### ISSUE TITLE
Some extra keybindings

### ISSUE THREAD

**Issue by darcamo** [dalanicolai/pdf-continuous-scroll-mode.el#9]
Great mode. It really helps.

Disclaimer: This is more like a suggestion to make pdf-continuous-scroll-mode nicer to use and mode consistent with pdf-tools. 

Since `pdf-continuous-scroll-mode` is a minor mode to be used with pdf-tools, if the user uses some keybinding that is not overwritten by `pdf-continuous-scroll-mode` the "magic" is lost and the two buffers lose sync.

I have defined some extra keybindinds that I use that could be included in `pdf-continuous-scroll-mode` by default.

```lisp
(define-key pdf-continuous-scroll-mode-map (kbd "<prior>") 'pdf-continuous-previous-page)
(define-key pdf-continuous-scroll-mode-map (kbd "<next>") 'pdf-continuous-next-page)
(define-key pdf-continuous-scroll-mode-map (kbd "q") '(lambda ()  (interactive) (pdf-continuous-scroll-mode -1) (quit-window) ))
```

I'm not a list programmer, but maybe pdf-continuous-scroll-mode could advice functions in pdf-tools to either work like usual if the minor mode is disabled, or like the equivalent function in `pdf-continuous-scroll-mode` if the minor mode is active. Then whatever keybinding the user sets in pdf-view-mode-map would work when `pdf-continuous-scroll-mode` is activated. Does this makes sense?

**Comment by dalanicolai** [comment]
Thanks for your suggestions. Greatly appreciated. I am using Spacemacs (i.e. evil-mode) myself, so these kind of suggestions really need to come from vanilla Emacs users. Your keybindings seem useful and sensible to me, so I will add them.
The idea about advising functions sounds nice, but indeed I am not sure if it makes sense. I am not sure if it is even possible to make things work using advice, and for sure it is easier to just write new functions. As this part of your suggestions has no priority for me, I do not find it worth the effort (time) for the little improvement. Also, I hope this package really is just a temporary solution, in the sense that I hope some better solution, like a canvas, will be implemented eventually (I think the [https://github.com/manateelazycat/emacs-application-framework](https://github.com/manateelazycat/emacs-application-framework) might already provide that final solution). But of course anybody is free to investigate it and contribute.
Anyway, thanks again for the feedback.

**Comment by darcamo** [comment]
Sure, no problem if this is not a priority or if it is never implemented. I just thought it was worth creating an issue in case it was simple to implement.

I also tried emacs-application-framework before finding your package. While it is great, at least for my main use case (PDFs generated from latex) it is lacking the feature of properly reverting the PDF when the file changes on disk. Your solution works much better for my use case.

Another small issue related to keybinding is scrolling with the mouse wheel when the buffer with the PDF is not active (when the active buffer is the one where I'm editing latex or org-mode, for instance). Because the buffer is not active, the mouse wheel will trigger the keybinding in the global-map thus calling `mwheel-scroll`, instead of the equivalent in pdf-continuous-scroll-mode. Of course I can just click the buffer first to make it active, but then I have to click my original Latex/org-mode buffer to continue writing.

**Comment by dalanicolai** [comment]
Closing the issue for archiving this repo. A better implementation is available at https://github.com/dalanicolai/image-roll.el
